version: "3"
services:
  web:    
    image: umeshk149/example:v2
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 200M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:

---------------------------

version: '3'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}